#!/bin/bash

rm -rf `find . -name CMakeFiles`
rm -rf `find . -name CMakeCache.txt`
rm -rf `find . -name cmake_install.cmake`
rm -rf `find . -name Makefile`
rm -rf `find . -name '*~'`
rm -rf `find . -name '*.o'`
rm -rf `find . -name '*.a'`
rm -rf `find . -name '*.so*'`
rm -rf `find . -name '*.mod'`
rm -rf bin/*
rm -rf lib/*
rm -rf mod/*
rm -rf tests/*/*.txt
